### PR TITLE
fix component transfer child attributes

### PR DESCRIPTION
**Pull request by luismarcelino**
Attributes for the componentTransfer filter were not set. This is a way to fix it.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
What is the code producing the error? Your fix unfortunately breaks other functionality

**Comment by luismarcelino** [comment]
Hi,
The child nodes of Component Filter do not get their attributes set and therefore the filter "does not work".
A simple example: https://jsfiddle.net/luismarcelino/u42qkL1y/

If you inspect the filter you do not get the filter attributes:
filter Gamma no attrs

, while you should get these results
filterGamma

Perhaps you have a better way to fix this without breaking anything.
Thanks, 
Luis

**Comment by Fuzzyma** [comment]
Can you please give me another example which actually produces the output you showed above? The jsfiddle is the a colorMatrix and not with a componentTransfer filter

**Comment by luismarcelino** [comment]
Sorry... I forgot to set the componentTransfer example as "base" in jsfiddle. Link should be fine now.
Thanks.

**Comment by Fuzzyma** [comment]
So the actual mistake is here: https://github.com/svgdotjs/svg.filter.js/blob/021c47b3a073d66e4692c537f66702710d5efd20/src/svg.filter.js#L60-L61

As you can see, `super(node, node)` is called. However, what it actually should be is `super(node, attrs)` and the constructor signature should be `constructor(node, attrs)`.

Would be cool, if you could test that

**Comment by luismarcelino** [comment]
The proposed fix works fine. Changes implemented in a different pull request (https://github.com/svgdotjs/svg.filter.js/pull/48)

**Pull request closed without merging**
